project:
  type: book

book:
  title: "Hands-on Large Scale Optimization in Python"
  # subtitle: "From Beginning to Giving Up"
  author: "Kunlei Lian"
  date: "2/18/2021"
  google-analytics: "G-XM4LXJY2KJ"
  favicon: logo.png
  twitter-card: true
  site-url: https://kunlei.github.io/large-scale-opt-python/
  # downloads: [pdf, epub]
  sharing: [twitter]
  # comments:
    # giscus:
      # repo: kunlei/large-scale-opt-python

  sidebar:
    style: docked
    background: light

  chapters:
    - index.qmd
    - introduction.qmd
    # - env-setup.qmd
    - part: "Benders Decomposition"
      chapters: 
        - benders-theory.ipynb
        - benders-linear-prog.ipynb
    - part: "Lagrangian Relaxation"
      chapters: 
        - lagrange-theory.ipynb
        - lagrange-assignment.ipynb
    - part: "Column Generation"
      chapters: 
        - cg-theory.ipynb
        - cg-cutting-stock.ipynb
        - cg-scheduling.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
    include-in-header: mathjax.html
    html-math-method: mathjax
  pdf:
    documentclass: scrreprt




